package chetan;
// Generated Mar 13, 2020 11:05:49 AM by Hibernate Tools 4.3.1



/**
 * Question generated by hbm2java
 */
public class Question  implements java.io.Serializable {


     private int id;
     private String qname;
     private String author;

    public Question() {
    }

	
    public Question(int id, String qname) {
        this.id = id;
        this.qname = qname;
    }
    public Question(int id, String qname, String author) {
       this.id = id;
       this.qname = qname;
       this.author = author;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getQname() {
        return this.qname;
    }
    
    public void setQname(String qname) {
        this.qname = qname;
    }
    public String getAuthor() {
        return this.author;
    }
    
    public void setAuthor(String author) {
        this.author = author;
    }




}


